= Edoxen

"Edoxen" is how all resolutions of Ancient Athens started.

____
"It was the opinion of... (the people and city that...)"
____


== Purpose

Edoxen is a set of information models used for representing resolution and
decision information.

The `edoxen` gem provides a library for accessing, writing and manipulating
the Edoxen information models, which can be serialized into a defined YAML
structure.


== Information models

The Edoxen information models are available at:

* https://github.com/metanorma/edoxen-model/


== Sample data

The following repositories contain Edoxen models in YAML:

* BIPM and CIPM body resolutions: https://github.com/metanorma/bipm-data-outcomes
* ISO/TC 154 resolutions: https://github.com/iso-tc154/resolutions-data


== Installation

Install the gem and add to the application's Gemfile by executing:

[source,sh]
----
$ bundle add edoxen
----

If bundler is not being used to manage dependencies, install the gem by
executing:

[source,sh]
----
$ gem install edoxen
----


== Usage


== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run
`rake spec` to run the tests. You can also run `bin/console` for an interactive
prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To
release a new version, update the version number in `version.rb`, and then run
`bundle exec rake release`, which will create a git tag for the version, push
git commits and the created tag, and push the `.gem` file to
https://rubygems.org.

== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/[USERNAME]/edoxen. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the https://github.com/[USERNAME]/edoxen/blob/main/CODE_OF_CONDUCT.md[code of conduct].

== Code of Conduct

Everyone interacting in the Edoxen project's codebases, issue trackers, chat
rooms and mailing lists is expected to follow the
https://github.com/[USERNAME]/edoxen/blob/main/CODE_OF_CONDUCT.md[code of conduct].
